version: '3.8'

services:
  backlink-indexer:
    build: .
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/indexer
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: indexer
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redis_data:/data

  selenium-hub:
    image: selenium/hub:4.15.0
    ports:
      - "4444:4444"

  selenium-chrome:
    image: selenium/node-chrome:4.15.0
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
    scale: 3

volumes:
  postgres_data:
  redis_data:
